 
//Deatils
export const POKEMON_DETAILS_REQUEST="POKEMON_DETAILS_REQUEST";
export const POKEMON_DETAILS_SUCCESS="POKEMON_DETAILS_SUCCESS";
export const POKEMON_DETAILS_FAILURE="POKEMON_DETAILS_FAILURE";